### PR TITLE
Dist

### PR DESCRIPTION
**Pull request by droom**

### CODE REVIEW

**Comment by droom** [comment]
files included in zip:

screen shot 2016-05-05 at 20 31 16

hope this is correct!

**Comment by pamelafox** [comment]
Cool, let's see if this work!

**Comment by pamelafox** [comment]
Tried uploading, apparently version is higher now: "Invalid version number in manifest: 1.92. Please make sure the newly uploaded package has a larger version in file manifest.json than the published package: 2.0.1." -- Can you up it?

**Comment by droom** [comment]
sure thing

**Comment by droom** [comment]
committed here under the same branch name:
https://github.com/pamelafox/font-previewer-extension/pull/8

**Pull request merged**
