### PR TITLE
updates icon set

### PR DESCRIPTION
**Pull request by droom**
I found the browser icon little hard to distinguish when scanning. This is my attempt to remedy! Icon set based on the Google 'G'. I think I've got all sizes covered.

fpe-diagram-icons-664

### CODE REVIEW

**Comment by pamelafox** [comment]
Neat!

**Comment by droom** [comment]
giphy

**Comment by pamelafox** [comment]
I unfortunately do not have a computer set up for developing right now, as I'm on a bit of a coding hiatus. That means it'll be a while until I get a new version uploaded. If you can package up the zip for upload, then I can do it sooner. (I think its a zip, right? It's been a while since I've updated extensions!)

**Comment by droom** [comment]
Hey @pamelafox, yep it's a zip packaged with Chrome I think.
Sure, I can do that. Should I create a dist/ folder and put the zip in there?

**Comment by pamelafox** [comment]
That sounds great, thank you!

**Comment by droom** [comment]
No worries. It's asking me for a private key file, which I think is needed to update an extension [according to the docs](https://developer.chrome.com/extensions/packaging). Should I continue without?

screen shot 2016-05-05 at 19 34 17

**Comment by pamelafox** [comment]
Hm from what I'm reading, the private key file is most important if you're
distributing it as a crx. I think it'll be okay without it. For dev store,
I just need a zip of the folder, not a packaged CRX file.

**Comment by droom** [comment]
ah ok, i'll just create a zip in the regular way

**Pull request merged**
